### ISSUE TITLE
Code for new benchmarks for 0.9.x

### ISSUE THREAD

**Issue by varunjammula** [carla-simulator/driving-benchmarks#2]
Is there an update on this issue?

**Comment by josiahcoad** [comment]
A new paper implemented these benchmarks for 0.9.6: [LearningByCheating](https://github.com/dianchen96/LearningByCheating)

**Comment by Suryavf** [comment]
There is a branch for 0.9.6: [`Link`](https://github.com/carla-simulator/driving-benchmarks/tree/carla_09_cexp)
